# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"

[plugins.zsh-abbr]
github = "olets/zsh-abbr"
use = ["{{ name }}.zsh"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.dotfiles-defer]
local = "~/dotfiles/zsh/defer"
use = ["*.zsh"]
apply = ["defer"]

[plugins.dotfiles-sync]
local = "~/dotfiles/zsh/sync"
use = ["*.zsh"]
apply = ["source"]
