name: linuxOS

on:
  push:
    paths:
      - 'Makefile'
      - 'scripts/*'
      - 'brew/*'

jobs:
  Linux-Setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: make all
      - name: Check commands
        run: zsh .github/scripts/check-commands.sh
