name: Setup CI

on:
  push:
    paths:
      - 'Makefile'
      - 'scripts/*'
      - 'brew/*'
      - '.github/*'

jobs:
  Setup:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - run: cp -r "$GITHUB_WORKSPACE" "$HOME"/dotfiles
      - run: make all
      - name: Check commands
        shell: /bin/zsh {0}
        run: .github/scripts/check-commands.sh
