name: Setup CI

on:
  push:
    paths:
      - 'Makefile'
      - 'scripts/*'
      - 'brew/*'

jobs:
  Setup:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - run: make all
      - name: Check commands
        run: zsh .github/scripts/check-commands.sh
